import Head from "next/head";
import Image from "next/image";
import Router, { useRouter } from "next/router";
import formImage from "../../public/form.png";
import { useFormik, FormikProps, yupToFormErrors } from "formik";
import * as Yup from "yup";
import { motion as m } from "framer-motion";

export default function Home() {
  interface formValues {
    name: string;
    email: string;
    country: string;
    terms: string;
  }

  const formik: FormikProps<formValues> = useFormik<formValues>({
    initialValues: {
      name: "",
      email: "",
      country: "United States",
      terms: "",
    },
    // validate form
    validationSchema: Yup.object({
      name: Yup.string()
        .max(20, "Name must be 20 characters or less")
        .required("Name is required"),
      email: Yup.string()
        .email("Invalid email address")
        .required("Email is required"),
      terms: Yup.boolean().oneOf([true], "This field must be checked"),
    }),
    // submit form
    onSubmit: (values) => {
      console.log(values);
      Router.push({ pathname: "/success", query: values });
    },
  });

  console.log(formik.values);
  console.log(formik.errors);

  return (
    <m.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="absolute w-full"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`h-screen flex items-center justify-center`}>
        <form
          onSubmit={formik.handleSubmit}
          className={`bg-white flex w-3/4 rounded-sm font-lato`}
        >
          <div className={`flex-1 text-gray-700 p-10`}>
            <h1 className={`font-lato font-bold`}>Let's get started 👋</h1>
            <p className={`text-lg text-gray-500`}>
              join our e-learning platform today and unlock over 400+ courses
              and digital asses ready to download.
            </p>
            <div className={`mt-6`}>
              <div className={`pb-4`}>
                <label
                  className={`block font-lato font-bold text-sm pb-2 ${
                    formik.touched.name && formik.errors.name
                      ? "text-red-400"
                      : ""
                  }`}
                  htmlFor="name"
                >
                  {formik.touched.name && formik.errors.name
                    ? formik.errors.name
                    : "Name"}
                </label>
                <input
                  className={`border-2 border-gray-500 p-2 rounded-md w-3/4 focus:border-teal-500 focus:ring-teal-500`}
                  type="text"
                  name="name"
                  placeholder="Enter your name"
                  value={formik.values.name}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                />
              </div>
              <div className={`pb-4`}>
                <label
                  className={`block font-lato font-bold text-sm pb-2 ${
                    formik.touched.email && formik.errors.email
                      ? "text-red-400"
                      : ""
                  }`}
                  htmlFor="email"
                >
                  {formik.touched.email && formik.errors.email
                    ? formik.errors.email
                    : "Email"}
                </label>
                <input
                  className={`border-2 border-gray-500 p-2 rounded-md w-3/4 focus:border-teal-500 focus:ring-teal-500`}
                  type="text"
                  name="email"
                  placeholder="Enter your email"
                  value={formik.values.email}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                />
              </div>
              <div className={`pb-4`}>
                <label
                  className={`block font-lato font-bold text-sm pb-2`}
                  htmlFor="country"
                >
                  Country
                </label>
                <select
                  value={formik.values.country}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                  className={`border-2 border-gray-500 w-3/4 p-2 rounded-md focus:border-teal-500 focus:ring-teal-500`}
                  name="country"
                >
                  <option value="United States">United States</option>
                  <option value="United Kingdom">United Kingdom</option>
                  <option value="Germany">Germany</option>
                  <option value="Sweden">Sweden</option>
                </select>
              </div>
              <div className={`pb-4`}>
                <label
                  className={`block font-lato font-bold text-sm pb-2 ${
                    formik.touched.terms && formik.errors.terms
                      ? "text-red-400"
                      : ""
                  }`}
                  htmlFor="terms"
                >
                  {formik.touched.terms && formik.errors.terms
                    ? formik.errors.terms
                    : "Terms"}
                </label>
                <div className={`flex items-center gap-2`}>
                  <input
                    type="checkbox"
                    name="terms"
                    value={formik.values.terms}
                    onChange={formik.handleChange}
                    className="h-5 w-5 text-teal-500 border-2  background-gray-500 focus:border-teal-500 focus:ring-teal-500"
                  />
                  <p className={`text-md text-gray-500`}>
                    I agree to the Term and Service that my data will be taken
                    and sold.
                  </p>
                </div>
              </div>
              <button
                type="submit"
                className="bg-teal-500 font-lato text-white py-3 mt-6 rounded-lg w-full"
              >
                Start Learning Today
              </button>
            </div>
          </div>
          <div className="flex-1 relative">
            <Image
              src={formImage}
              alt="form-learn"
              className="object-cover rounded-sm"
              fill
              priority
            />
          </div>
        </form>
      </main>
    </m.div>
  );
}
